Traceback (most recent call last):
  File "C:\Users\19lss3\financial_labeling\rq3\rq3_test.py", line 70, in <module>
    test_results = task_evaluator.compute(model_or_pipeline=classifier_pipeline, data=test_dataset, metric="seqeval")
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ProgramData\Anaconda3\envs\financial_labeling\Lib\site-packages\evaluate\evaluator\token_classification.py", line 262, in compute
    predictions = self.predictions_processor(predictions, data[input_column], join_by)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ProgramData\Anaconda3\envs\financial_labeling\Lib\site-packages\evaluate\evaluator\token_classification.py", line 132, in predictions_processor
    while prediction[token_index]["start"] < word_offset[0]:
          ~~~~~~~~~~^^^^^^^^^^^^^
IndexError: list index out of range